version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "nodejs",
    "browser"
  ]
  skip_doc_coverage = ["class-expression", "method-definition"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"