export const DAYS = {
	poniedziałek: 0,
	wtorek: 1,
	środa: 2,
	czwartek: 3,
	piątek: 4,
};

export const LESSONS = {
	wf: 'WF',
	wos: 'WOS',
	matematyka: 'Matematyka',
	r_matematyka: 'Matematyka (R)',
	'j.polski': 'J. Polski',
	'j.angielski': 'J. Angielski',
	r_angielski: 'J. Angielski (R)',
	'j.niemiecki': 'J. Niemiecki',
	informatyka: 'Informatyka',
	'r_informat.': 'Informatyka (R)',
	fizyka: 'Fizyka',
	r_fizyka: 'Fizyka (R)',
	u_fizyka: 'Fizyka (U)',
	geografia: 'Geografia',
	r_geografia: 'Geografia (R)',
	biologia: 'Biologia',
	historia: 'Historia',
	chemia: 'Chemia',
	e_dla_bezp: 'EDB',
	Fil: 'Filozofia',
	religia: 'Religia',
  'u_hist.i sp.': 'Hist. i Sp. (U)',
	'przedsięb.': 'Przedsiębiorczość',
	'zaj. wych.': 'L. Wychowawcza',
	'godz. wych.': 'L. Wychowawcza',
};

export const TEACHERS = {
	'S.Świetlik (SS)': 'Śławomir Świetlik (SS)',
	'B.Piękoś-Kwolek (BP)': 'Bożena Piękoś-Kwolek (BP)',
	'A.Romaszuk (RA)': 'Alicja Romaszuk (RA)',
	'A.Kulasa (KU)': 'Andrzej Kulasa (KU)',
	'I.Adamiec-Zielińska (IZ)': 'Iwona Adamiec-Zielińska (IZ)',
	'A.Aeroklub Rzeszowski (AA)': 'Aeroklub Rzeszowki (AA)',
	'M.Bajor (MB)': 'Monika Bajor (MB)',
	'M.Bardzik (BR)': 'Magdalena Bardzik (BR)',
	'A.Bartyzel (AB)': 'Alicja Bartyzel (AB)',
	'M.Berrahal (BM)': 'Mariola Berrahal (BM)',
	'N.Bołba (NK)': 'N. Bołba (NK)', // Brak rozwinięcia
	'B.Brzęk (BB)': 'Barbara Brzęk (BB)',
	'A.Buć (Bu)': 'Agnieszka Buć (Bu)',
	'c.Centrum Kształcenia Zawodowego (CK)': 'Centrum Kształcenia Zawodowego (CK)',
	'J.Cichoń (JC)': 'Joanna Cichoń (JC)',
	'P.Cyrek (CY)': 'P. Cyrek (CY)', // Brak rozwinięcia
	'B.Czach (CB)': 'Bogdan Czach (CY)',
	'P.Czajor (CP)': 'Piotr Czajor (CP)',
	'A.Czechowicz (CZ)': 'Agata Czechowicz (CZ)',
	'A.Domagała (LA)': 'Anna Domagała (LA)',
	'E.Dragulska (ED)': 'Edyta Dragulska (ED)',
	'M.Drozd (DO)': 'Mariusz Drozd (DO)',
	'A.Dytko (DA)': 'Adam Dytko (DA)',
	'E.Emeaero (EE)': 'E. Emeaero (EE)', // Brak rozwinięcia
	'A.Frydrych (AF)': 'Andrzej Frydrych (AF)',
	'M.Gorol (MG)': 'M. Gorol (MG)', // Brak rozwinięcia
	'O.Gorol (OG)': 'O. Gorol (OG)', // Brak rozwinięcia
	'D.Grudziński (DG)': 'Dawid Grudziński (DG)',
	'L.Grzesik (LG)': 'Leokadia Grzesik (LG)',
	'M.Haber (HM)': 'Marek Haber (HM)',
	'B.Hałucha  (BH)': 'Bożena Hałucha (BH)',
	'H.Heli One (HO)': 'Heli One (HO)',
	'A.Kapłon (KA)': 'Agnieszka Kapłon (KA)',
	'B.Kataniak-Stefańska (SB)': 'Bożena Kataniak-Stefańska (SB)',
	'E.Kijowska (GV)': 'E. Kijowska (GV)', // Brak rozwinięcia
	'M.Kisiel (MK)': 'Mariusz Kisiel (MK)',
	'Z.Kłeczek (ZK)': 'Zdzisław Kłeczek (ZK)',
	'K.Kołodziej (KR)': 'K. Kołodziej (KR)', // Brak rozwinięcia
	'M.Kołodziej (KI)': 'Magdalena Kołodziej (KI)',
	'P.Korbecki (KE)': 'Piotr Korbecki (KE)',
	'A.Kot (KT)': 'Alicja Kot (KT)',
	'M.Kot-Nowicka (MN)': 'Magdalena Kot-Nowicka (MN)',
	'D.Kotowicz (DK)': 'D. Kotowicz (DK)', // Brak rozwinięcia
	'J.Kozicki (KC)': 'J. Kozicki (KC)', // Brak rozwinięcia
	'I.Krużel (IK)': 'Iwona Krużel (IK)',
	'W.Kubala (KB)': 'Wojciech Kubala (KB)',
	'D.Kustra (KD)': 'Dorota Kustra (KD)',
	'L.LineTech (LL)': 'LineTech (LL)',
	'K.Lizak (LK)': 'Kinga Lizak (LK)',
	'D.Łagowska (DL)': 'Dorota Łagowska (DL)',
	'S.Łoboda  (SŁ)': 'Sławomir Łoboda (SŁ)',
	'W.Machowska (WM)': 'Wioletta Machowska (WM)',
	'D.Michnia (MI)': 'Dorota Michnia (MI)',
	'M.Mucha (MU)': 'Marta Mucha (MU)',
	'J.Nazarko (JN)': 'Jolanta Nazarko (JN)',
	'A.Nazimek (NA)': 'Adam Nazimek (NA)',
	'J.Pasterz (JU)': 'Justyna Pasterz (JU)',
	'A.Pawlak (AP)': 'Agata Pawlak (AP)',
	'E.Pitera (EP)': 'Elżbieta Pitera (EP)',
	'J.Płonka (PŁ)': 'Jarosław Płonka (PŁ)',
	'K.Potoczna (KP)': 'Krystyna Potoczna (KP)',
	'P.Pratt Whitney AeroPower (PT)': 'Pratt & Whitney AeroPower (PT)',
	'C.Prokop (PK)': 'Cezary Prokop (PK)',
	'D.Prokopik (DP)': 'Daniel Prokopik (DP)',
	'P.Pustelny (PP)': 'Piotr Pustelny (PP)',
	'P.Rosa (RP)': 'Paweł Rosa (RP)',
	'G.Różycki (RG)': 'Grzegorz Różycki (RG)',
	'S.Salony fryzjerskie (FR)': 'Salony fryzjerskie (FR)',
	'B.Stadnik (BS)': 'B. Stadnik (BS)', // Brak rozwinięcia
	'S.Stawarz (ST)': 'Sławomir Stawarz (ST)',
	'L.Sulencka (SL)': 'Lucyna Sulencka (SL)',
	'E.Surowiec (SR)': 'Ewelina Surowiec (SR)',
	'S.Szcząchor (SC)': 'Sebastian Szcząchor (SC)',
	'S.Szela (SE)': 'Stanisław Szela (SE)',
	'I.Szetela (IS)': 'Ilona Szetela (IS)',
	'U.Szpuga (SU)': 'Urszula Szpuga (SU)',
	'E.Świder (ES)': 'Ewa Świder (ES)',
	'S.Topolewicz (TO)': 'Stanisław Topolewicz (TO)',
	'A.Uchman (UA)': 'Agnieszka Uchman (UA)',
	'E.Wojakowska (WE)': 'Ewa Wojakowska (WE)',
	'M.Wojtaszek-Hudzik (MW)': 'Magdalena Wojtaszek-Hudzik (MW)',
	'M.Wiśniowska (WI)': 'Monika Wiśniowska (WI)',
	'P.Zwiercan (ZW)': 'P. Zwiercan (ZW)', // Brak rozwinięcia
	'p.vacat (PV)': 'Vacat (PV)',
	'r.vacat (VR)': 'Vacat (VR)',
	'W.vacat (VW)': 'Vacat (VW)',
};
